name: JAVA-MAVEN-CONTAINER-01
on: push

jobs:
  validate:
    name: Workflow Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
         sign_value=$(md5sum ./.github/workflows/main.yml)
         sign_value=$(echo $sign_value|cut -f1 -d' '|tr -s ' ')
         echo $sign_value
         ref_value=$(cat ./checksum)
         echo $ref_value
         if [ "$ref_value" != "$sign_value" ]; then
            echo "Workflow failed as workflow yaml is not compliant with the standards set."
            exit 1
         fi
        name: workflow compliance checker 
  build:
    name: Hello world action
    needs: [ validate ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Govind"
      - run: sleep 30
