name: JAVA-MAVEN-CONTAINER-01
on: push

jobs:
  validate:
    name: Workflow Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: md5sum ./.github/workflows/main.yml

  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Govind"
      - run: sleep 600
