name: A workflow for my Hello World file
on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Jira id validator
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Jira issue id extractor
      id: run_tests
      uses: TheRealWaldo/jira-get-issue@v0.0.2
      with:
        search-string: ${{github.event.head_commit.message}}
    - name: Print Jira id
      run: |
         echo ${{steps.run_tests.outputs.issue-key}}
    - name: Print env
      run: |
         echo ${{github.event.head_commit.message}}
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
